### ISSUE TITLE
CLI should be possible to run in non-interactive mode

### ISSUE THREAD

**Issue by stranger80** [NethermindEth/entro#8]
Running `entro backfill starknet full-blocks --from-block 600000 --to-block 600500 --block-file=...` requires user interaction/confirmation. This makes it impossible to configure the usage of the CLI in batching workflow platforms.

It should be possible to run data extraction in fully non-interactive mode.

**Comment by elicbarbieri** [comment]
added --no-interaction CLI flag to disable backfill confirmation & progress bar display.  Will be merged into master
